version: "3.7"
services:
  ventilator:
    build: ventilator
    network_mode: "host"        
  sink:
    build: sink
    depends_on:
      - ventilator
      - minio
    network_mode: "host"        
  worker0:
    build: worker
    depends_on:
        - ventilator
        - sink
    network_mode: "host"        
  worker1:
    build: worker
    depends_on:
        - ventilator
        - sink
    network_mode: "host"        
  worker2:
    build: worker
    depends_on:
        - ventilator
        - sink
    network_mode: "host"
  worker3:
    build: worker
    depends_on:
        - ventilator
        - sink
    network_mode: "host" 
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data      
volumes:
  minio_storage: {}
