version: "3.7"
services:
  data_generator:
    build: data_generator
    network_mode: "host"
    container_name: data_generator
    depends_on:
      - zookeeper
      - broker
  data_receiver:
    build: data_receiver
    network_mode: "host"
    container_name: data_receiver
    depends_on:
      - data_generator
      - zookeeper
      - broker
  fraud_classifier_1:
    build: fraud_classifier
    network_mode: "host"
    container_name: fraud_classifier_1
    depends_on:
      - data_generator
      - data_receiver
      - zookeeper
      - broker
  fraud_classifier_2:
    build: fraud_classifier
    network_mode: "host"
    container_name: fraud_classifier_2
    depends_on:
      - data_generator
      - data_receiver
      - zookeeper
      - broker
  fraud_classifier_3:
    build: fraud_classifier
    network_mode: "host"
    container_name: fraud_classifier_3
    depends_on:
      - data_generator
      - data_receiver
      - zookeeper
      - broker
  fraud_listener:
    build: fraud_listener
    network_mode: "host"
    container_name: fraud_listener
    depends_on:
      - zookeeper
      - broker
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost